### ISSUE TITLE
import should work with rule templates

### ISSUE THREAD

**Issue by ganncamp** [SonarQubeCommunity/sonar-checkstyle#27]
With SonarQube 4.5.1 and Checkstyle plugin 2.2, importing the following file triggers an error: "Rule template can't be activated on a Quality profile: checkstyle:com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineJavaCheck"
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
 
<module name="Checker">
  <module name="TreeWalker">
    <module name="RegexpSinglelineJava">
      <!-- . matches any character, so we need to
         escape it and use \. to match dots. -->
      <property name="format" value="System\.out\.println"/>
      <property name="ignoreComments" value="true"/>
    </module>
  </module>
</module>
```
ML ref: http://sonarqube.15.x6.nabble.com/Cannot-import-Checkstyle-configuration-with-RegexpSinglelineJava-module-td5031006.html#none

**Comment by m-g-sonar** [comment]
This repository is now closed.
Please continue this thread on the new repository of the checkstyle plugin: https://github.com/checkstyle/sonar-checkstyle/issues/2
