### ISSUE TITLE
Unable to import Google Style Gude ruleset 

### ISSUE THREAD

**Issue by jakub-bochenski** [SonarQubeCommunity/sonar-checkstyle#31]
When trying to import https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml I get 

> 
> We're sorry, but something went wrong.
> 
> Please try back in a few minutes and contact support if the problem persists.
> 
> Go back to the homepage

**Comment by jakub-bochenski** [comment]
I think this is the cause:
```
2016.04.14 12:39:59 ERROR web[o.s.s.ui.JRubyFacade] Fail to render: https://sonar.egnyte-internal.com/profiles/create
The definition of the profile 'null' (language 'null') contains multiple occurrences of the 'checkstyle:com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck' rule. The plugin which declares this profile should fix this.
```

**Comment by jakub-bochenski** [comment]
I had to remove
```
        <module name="AnnotationLocation">
            <property name="tokens" value="VARIABLE_DEF"/>
            <property name="allowSamelineMultipleAnnotations" value="true"/>
        </module>
and
        <module name="RightCurly">
            <property name="option" value="alone"/>
            <property name="tokens" value="CLASS_DEF, METHOD_DEF, CTOR_DEF, LITERAL_FOR, LITERAL_WHILE, LITERAL_DO, STATIC_INIT, INSTANCE_INIT"/>
        </module>
```

Then it created the profile with a cryptic error:
> Rule template can't be activated on a Quality profile: checkstyle:com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCheck

**Comment by jakub-bochenski** [comment]
Removing this:
```
        <module name="IllegalTokenText">
            <property name="tokens" value="STRING_LITERAL, CHAR_LITERAL"/>
            <property name="format" value="\\u00(08|09|0(a|A)|0(c|C)|0(d|D)|22|27|5(C|c))|\\(0(10|11|12|14|15|42|47)|134)"/>
            <property name="message" value="Avoid using corresponding octal or Unicode escape."/>
        </module>
```
and
```
        <module name="NoLineWrap"/>
```

Results in 
> Value ' LITERAL_FINALLY' must be one of : LITERAL_WHILE, LITERAL_TRY, LITERAL_CATCH, LITERAL_FINALLY, LITERAL_DO, LITERAL_IF, LITERAL_ELSE, LITERAL_FOR, INSTANCE_INIT, STATIC_INIT, LITERAL_SWITCH, LITERAL_SYNCHRONIZED, LITERAL_CASE, LITERAL_DEFAULT, ARRAY_INIT.   

Which doesn't make sense.

**Comment by jakub-bochenski** [comment]
Removing spaces between elements fixed that resulting in:
> Value ' TEXT' must be one of : text,stmnt
after lowercasing it I hit
> Rule template can't be activated on a Quality profile: checkstyle:com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck  

so I've removed 
```
        <module name="NeedBraces"/>
```
resulting in:

> Rule template can't be activated on a Quality profile: checkstyle:com.puppycrawl.tools.checkstyle.checks.blocks.LeftCurlyCheck  

I'm giving up now as the ruleset is useless with so many changes.

**Comment by m-g-sonar** [comment]
This repository is now closed.
Please continue this thread on the new repository of the checkstyle plugin: https://github.com/checkstyle/sonar-checkstyle/issues/5
